name: Lint

on:
  release:
    types: [published]
  push:
    branches:
      - main
      - develop
      - "**"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          uv pip install --system -e ".[dev]"

      - name: Run black (format check)
        run: |
          black --check src/ tests/

      - name: Run flake8
        run: |
          flake8 src/ tests/

      - name: Run mypy
        run: |
          mypy src/ || true  # Don't fail on type errors yet

      - name: Run bandit (security)
        run: |
          bandit -r src/ -f json -o bandit-report.json || true
          bandit -r src/

